module.exports = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    INVALID_PURCHASE_HANDLER: 'INVALID_PURCHASE_HANDLER',
    INVALID_AUTHENTICATION: 'INVALID_AUTHENTICATION',
    INVALID_SERVICE_KEY: 'INVALID_SERVICE_KEY',
    INVALID_BODY: 'INVALID_BODY',
    DISTRIBUTOR_UNAVAILABLE: 'DISTRIBUTOR_UNAVAILABLE',
    SERVICE_TEMPORARILY_UNAVAILABLE: 'SERVICE_TEMPORARILY_UNAVAILABLE',
    INVALID_REQUEST: 'INVALID_REQUEST',
    PREVALIDATION_FAILED: 'PREVALIDATION_FAILED',
    SUCCESS: 'SUCCESS'
}
