module.exports = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    INVALID_AUTHENTICATION: 'INVALID_AUTHENTICATION',
    INVALID_SERVICE_KEY: 'INVALID_SERVICE_KEY',
    INVALID_BODY: 'INVALID_BODY',
    INVALID_REQUEST: 'INVALID_REQUEST',
    SUCCESS: 'SUCCESS'
}
